version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/Tech-O-Dex
hooks:
  ApplicationStart:
    - location: scripts/runapp.sh
      runas: ec2-user
  ValidateService:
    - location: scripts/verifyapp.sh
      runas: root
